### ISSUE TITLE
No Demo or Code?

### ISSUE THREAD

**Issue by njtierney** [uwdata/bayesian-surprise#1]
Hi guys!

Great looking paper! Found it on twitter/Medium.

I just noted that in your README you state that there is a code and demo directory, but the links to don't seem to point to a current directory? I understand that sometimes it can be tricky to share this sort of information, do you think you will be able to share it on GitHub eventually?

Also, really cool to find a paper on Twitter, read about it on Medium, then find a GitHub repo that contains the paper and figures. Great Job!

**Comment by mcorrell** [comment]
We are in the process of migrating the code over from a private repo to this public one, and (in the process) making a more public-facing demo. We will have things up and running before the VIS conference in late October at the latest!

**Comment by njtierney** [comment]
Awesome! Very exciting. Once again, great job! :)

**Comment by maculatus** [comment]
Hello,
I was wondering if the code is going to be available? Great work. Cheers

**Comment by mcorrell** [comment]
Yes! By Thursday at the latest.

**Comment by maculatus** [comment]
Great!
